//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeCare.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public Nullable<int> IdMacAddress { get; set; }
        public string Steps { get; set; }
        public Nullable<System.DateTime> GettingDateFrom { get; set; }
        public Nullable<System.DateTime> GettingDateTo { get; set; }
        public string Intensity { get; set; }
        public string Category { get; set; }
        public string HeartRate { get; set; }
    }
}
