//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeCare.Api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakeCareEntities : DbContext
    {
        public TakeCareEntities()
            : base("name=TakeCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activities> Activities1 { get; set; }
        public virtual DbSet<Carers> Carers { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Person1> Person1Set { get; set; }
    }
}
